apiVersion: v1
kind: Service
metadata:
  labels:
    app: zk
  name: zk-cs
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: client
      port: 2181
      protocol: TCP
      targetPort: 2181
  selector:
    app: zk
  sessionAffinity: None
  type: ClusterIP
