version: '3.7'
services:
  nginx:
    image: nginx:1.23.2
    restart: unless-stopped
    container_name: app_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cert:/etc/nginx/cert
      - ./nginx/www:/var/www
      - ./nginx/logs:/var/logs