apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: data
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: console
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: minio
  sessionAffinity: None
  type: ClusterIP
