apiVersion: v1
kind: Service
metadata:
  name: ss-server-np
  namespace: aireport
spec:
  ports:
    - name: tcp-port
      nodePort: 32156
      port: 8388
      protocol: TCP
      targetPort: 8388
    - name: upd-port
      nodePort: 32156
      port: 8388
      protocol: UDP
      targetPort: 8388
  selector:
    app: ss-server
  sessionAffinity: None
  type: NodePort
