apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    role: mongo
  sessionAffinity: None
  type: ClusterIP
