apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka-svc
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: server
      port: 9093
      protocol: TCP
      targetPort: 9093
  selector:
    app: kafka
  sessionAffinity: None
  type: ClusterIP
