version: "3.7"
services:
  mongodb:
    image: mongo:4.4.0
    container_name: mongo
    command: [--auth]
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db
      - ./log:/var/log/mongodb  # 挂载日志目录
      - ./config:/etc/mongo  # 挂载配置目录
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=AFGXmP2Js0NnkCIc