apiVersion: v1
data:
  master.cnf: |-
    # Master配置
    [mysqld]
    log-bin=mysqllog
    skip-name-resolve
    lower_case_table_names=1
    local-infile=0
    symbolic-links=0
    max_allowed_packet = 1024M

    character-set-server=utf8

    max_connections=10000

    sql_mode = STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
  slave.cnf: |-
    # Slave配置
    [mysqld]
    super-read-only
    skip-name-resolve
    log-bin=mysql-bin
    replicate-ignore-db=mysql
kind: ConfigMap
metadata:
  labels:
    app: mysql
  name: mysql
