apiVersion: v1
kind: Service
metadata:
  name: nacos-np
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http01
      nodePort: 30858
      port: 8848
      protocol: TCP
      targetPort: 8848
  selector:
    app: nacos
  sessionAffinity: None
  type: NodePort
