apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq-cluster
  name: rabbitmq-cluster
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: rmqport
      port: 5672
      protocol: TCP
      targetPort: 5672
  selector:
    app: rabbitmq-cluster
  sessionAffinity: None
  type: ClusterIP
