apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq-cluster
  name: rabbitmq-cluster-manage
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      nodePort: 1066
      port: 15672
      protocol: TCP
      targetPort: 15672
  selector:
    app: rabbitmq-cluster
  sessionAffinity: None
  type: NodePort
